### ISSUE TITLE
Partition layout?

### ISSUE THREAD

**Issue by unresolvedsymbol** [EmreTech/Unofficial-Switchroot-Android-Q-Builds#4]
This would be useful for anyone who already knows how to resize and move partitions themselves without having to backup and restore data.

**Comment by EmreTech** [comment]
There isn't a known way to make a partition for Android Q without wiping your SD Card to my knowledge.

**Comment by unresolvedsymbol** [comment]
Can you at least show me the `lsblk -f` output with a correctly partitioned SD
